
networks:
  milvus_network:
    driver: bridge

services:
  etcd:
    container_name: milvus-standalone-etcd-1
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
      - ETCD_ENABLE_V2=false
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_INITIAL_CLUSTER=etcd=http://etcd:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
    networks:
      - milvus_network
    volumes:
      - etcd-data:/etcd

  minio:
    container_name: milvus-standalone-minio-1
    image: minio/minio:RELEASE.2024-03-30T09-41-56Z
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: server /minio_data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/minio_data
    networks:
      - milvus_network

  milvus-standalone:
    platform: linux/amd64
    container_name: milvus-standalone-standalone-1
    image: milvusdb/milvus:v2.2.12
    command: ["milvus", "run", "standalone"]
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus
    environment:
      - ETCD_ENDPOINTS=etcd:2379
    depends_on:
      - etcd
      - minio
    networks:
      - milvus_network
    extra_hosts:
      - "etcd:127.0.0.1"  # Just in case DNS fails
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  mcp-server:
    container_name: milvus-standalone-mcp-server-1
    build:
      context: .
      dockerfile: Dockerfile.mcp
    volumes:
      - .:/app
    depends_on:
      - milvus-standalone
    ports:
      - "8000:8000"
    environment:
      - MILVUS_URI=http://standalone:19530
      - MILVUS_DB=default
    networks:
      - milvus_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  milvus_data:
  etcd-data:
  minio_data:
